USE [master]
GO
/****** Object:  Database [SqlInjDemo]    Script Date: 2019/04/19 15:45:22 ******/
CREATE DATABASE [SqlInjDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SqlInjDemo', FILENAME = N'/var/opt/mssql/data/SqlInjDemo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SqlInjDemo_log', FILENAME = N'/var/opt/mssql/data/SqlInjDemo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SqlInjDemo] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SqlInjDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SqlInjDemo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SqlInjDemo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SqlInjDemo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SqlInjDemo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SqlInjDemo] SET ARITHABORT OFF 
GO
ALTER DATABASE [SqlInjDemo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SqlInjDemo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SqlInjDemo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SqlInjDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SqlInjDemo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SqlInjDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SqlInjDemo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SqlInjDemo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SqlInjDemo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SqlInjDemo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SqlInjDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SqlInjDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SqlInjDemo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SqlInjDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SqlInjDemo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SqlInjDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SqlInjDemo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SqlInjDemo] SET RECOVERY FULL 
GO
ALTER DATABASE [SqlInjDemo] SET  MULTI_USER 
GO
ALTER DATABASE [SqlInjDemo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SqlInjDemo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SqlInjDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SqlInjDemo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SqlInjDemo] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'SqlInjDemo', N'ON'
GO
ALTER DATABASE [SqlInjDemo] SET QUERY_STORE = OFF
GO
USE [SqlInjDemo]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 2019/04/19 15:45:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[Email] [nvarchar](200) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Users] ON 

INSERT [dbo].[Users] ([UserId], [Name], [Email]) VALUES (1, N'Somebody', N'Somebody@email.com')
INSERT [dbo].[Users] ([UserId], [Name], [Email]) VALUES (2, N'Someone Else', N'SomebodyElse@email.com')
SET IDENTITY_INSERT [dbo].[Users] OFF
USE [master]
GO
ALTER DATABASE [SqlInjDemo] SET  READ_WRITE 
GO
